### ISSUE TITLE
Create file of CP plugin that can be uploaded to Marketplace

### ISSUE THREAD

**Issue by JennyMeissner** [CommandPost/LoupedeckPlugin#25]
Create a lplug4 file of CP plugin that can be uploaded to Marketplace. Include a default profile with pre-assigned actions to be used in FCP app. The default profile is to be delivered still.

(Let's see a LINK to the CP plugin as minimum viable solution. Pauli would be ok with that solution, but from user's point of view, let's make it as straight forward as possible:

Ideally, users can simply click the Install button in Marketplace and can start using the plugin when installation has finished.)

**Comment by latenitefilms** [comment]
I think having the plugin installed from Marketplace will actually be more confusing, because users will still need to install CommandPost. It also then requires the Marketplace Plugin to be at the same version as the CommandPost version.

I think it would be much cleaner/simpler/easier if we just kept the Loupedeck Plugin within CommandPost, then we know for certain that the Loupedeck Plugin will work with the installed version of CommandPost.

How do developers upload new versions to the Loupedeck Marketplace? Is it a manual process where we just need to email Loupedeck a new ZIP? If so, that's another disadvantage, because if we want to push out an update quickly, we're then waiting on Loupedeck.

**Comment by latenitefilms** [comment]
I'm going to close this for now as I believe the general consensus is that we'll just keep the Loupedeck Plugin embedded within the CommandPost application. Feel free to re-open if you disagree.
